# Generated by Django 6.0.5 on 2026-05-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_alter_dish_options_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
